# Generated by Django 2.2.19 on 2023-04-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('user', 'recipe'), 'verbose_name': 'Список покупок', 'verbose_name_plural': 'Список покупок'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('slug',), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
